/*
ArvanCloud CDN Services

Testing ActiveHealthCheckApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package r1cdn

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/arvancloud/cdn-go"
)

func Test_r1cdn_ActiveHealthCheckApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ActiveHealthCheckApiService ActiveHealthCheckDestroy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string
		var healthcheck string

		resp, httpRes, err := apiClient.ActiveHealthCheckApi.ActiveHealthCheckDestroy(context.Background(), domain, healthcheck).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActiveHealthCheckApiService ActiveHealthCheckIndex", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string

		resp, httpRes, err := apiClient.ActiveHealthCheckApi.ActiveHealthCheckIndex(context.Background(), domain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActiveHealthCheckApiService ActiveHealthCheckReportsDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string

		resp, httpRes, err := apiClient.ActiveHealthCheckApi.ActiveHealthCheckReportsDetails(context.Background(), domain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActiveHealthCheckApiService ActiveHealthCheckReportsSummary", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string

		resp, httpRes, err := apiClient.ActiveHealthCheckApi.ActiveHealthCheckReportsSummary(context.Background(), domain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActiveHealthCheckApiService ActiveHealthCheckShow", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string
		var healthcheck string

		resp, httpRes, err := apiClient.ActiveHealthCheckApi.ActiveHealthCheckShow(context.Background(), domain, healthcheck).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActiveHealthCheckApiService ActiveHealthCheckStore", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string

		resp, httpRes, err := apiClient.ActiveHealthCheckApi.ActiveHealthCheckStore(context.Background(), domain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActiveHealthCheckApiService ActiveHealthCheckUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string
		var healthcheck string

		resp, httpRes, err := apiClient.ActiveHealthCheckApi.ActiveHealthCheckUpdate(context.Background(), domain, healthcheck).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ActiveHealthCheckApiService HealthChecksZonesIndex", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ActiveHealthCheckApi.HealthChecksZonesIndex(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
