/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.99.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package r1cdn

import (
	"encoding/json"
)

// checks if the WafPackageProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WafPackageProvider{}

// WafPackageProvider struct for WafPackageProvider
type WafPackageProvider struct {
	Name *string `json:"name,omitempty"`
	Logo *string `json:"logo,omitempty"`
}

// NewWafPackageProvider instantiates a new WafPackageProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWafPackageProvider() *WafPackageProvider {
	this := WafPackageProvider{}
	return &this
}

// NewWafPackageProviderWithDefaults instantiates a new WafPackageProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWafPackageProviderWithDefaults() *WafPackageProvider {
	this := WafPackageProvider{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WafPackageProvider) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafPackageProvider) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WafPackageProvider) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WafPackageProvider) SetName(v string) {
	o.Name = &v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *WafPackageProvider) GetLogo() string {
	if o == nil || IsNil(o.Logo) {
		var ret string
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafPackageProvider) GetLogoOk() (*string, bool) {
	if o == nil || IsNil(o.Logo) {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *WafPackageProvider) HasLogo() bool {
	if o != nil && !IsNil(o.Logo) {
		return true
	}

	return false
}

// SetLogo gets a reference to the given string and assigns it to the Logo field.
func (o *WafPackageProvider) SetLogo(v string) {
	o.Logo = &v
}

func (o WafPackageProvider) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WafPackageProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	return toSerialize, nil
}

type NullableWafPackageProvider struct {
	value *WafPackageProvider
	isSet bool
}

func (v NullableWafPackageProvider) Get() *WafPackageProvider {
	return v.value
}

func (v *NullableWafPackageProvider) Set(val *WafPackageProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableWafPackageProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableWafPackageProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWafPackageProvider(val *WafPackageProvider) *NullableWafPackageProvider {
	return &NullableWafPackageProvider{value: val, isSet: true}
}

func (v NullableWafPackageProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWafPackageProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


