/*
ArvanCloud CDN Services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.99.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package r1cdn

import (
	"encoding/json"
)

// checks if the LogForwardersIndex200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogForwardersIndex200Response{}

// LogForwardersIndex200Response struct for LogForwardersIndex200Response
type LogForwardersIndex200Response struct {
	Data []LogForwarderSummary `json:"data,omitempty"`
	Links *PaginatedResponseLinks `json:"links,omitempty"`
	Meta *PaginatedResponseMeta `json:"meta,omitempty"`
}

// NewLogForwardersIndex200Response instantiates a new LogForwardersIndex200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogForwardersIndex200Response() *LogForwardersIndex200Response {
	this := LogForwardersIndex200Response{}
	return &this
}

// NewLogForwardersIndex200ResponseWithDefaults instantiates a new LogForwardersIndex200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogForwardersIndex200ResponseWithDefaults() *LogForwardersIndex200Response {
	this := LogForwardersIndex200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *LogForwardersIndex200Response) GetData() []LogForwarderSummary {
	if o == nil || IsNil(o.Data) {
		var ret []LogForwarderSummary
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogForwardersIndex200Response) GetDataOk() ([]LogForwarderSummary, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *LogForwardersIndex200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []LogForwarderSummary and assigns it to the Data field.
func (o *LogForwardersIndex200Response) SetData(v []LogForwarderSummary) {
	o.Data = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *LogForwardersIndex200Response) GetLinks() PaginatedResponseLinks {
	if o == nil || IsNil(o.Links) {
		var ret PaginatedResponseLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogForwardersIndex200Response) GetLinksOk() (*PaginatedResponseLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *LogForwardersIndex200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given PaginatedResponseLinks and assigns it to the Links field.
func (o *LogForwardersIndex200Response) SetLinks(v PaginatedResponseLinks) {
	o.Links = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *LogForwardersIndex200Response) GetMeta() PaginatedResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret PaginatedResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogForwardersIndex200Response) GetMetaOk() (*PaginatedResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *LogForwardersIndex200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PaginatedResponseMeta and assigns it to the Meta field.
func (o *LogForwardersIndex200Response) SetMeta(v PaginatedResponseMeta) {
	o.Meta = &v
}

func (o LogForwardersIndex200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogForwardersIndex200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableLogForwardersIndex200Response struct {
	value *LogForwardersIndex200Response
	isSet bool
}

func (v NullableLogForwardersIndex200Response) Get() *LogForwardersIndex200Response {
	return v.value
}

func (v *NullableLogForwardersIndex200Response) Set(val *LogForwardersIndex200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableLogForwardersIndex200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableLogForwardersIndex200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogForwardersIndex200Response(val *LogForwardersIndex200Response) *NullableLogForwardersIndex200Response {
	return &NullableLogForwardersIndex200Response{value: val, isSet: true}
}

func (v NullableLogForwardersIndex200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogForwardersIndex200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


